export const PRODUCT_DEFAULT_IMAGE =
  'https://saunuivsvyipdlbeqqud.supabase.co/storage/v1/object/sign/product-images/products/product-default-image.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9wcm9kdWN0cy9wcm9kdWN0LWRlZmF1bHQtaW1hZ2UuanBnIiwiaWF0IjoxNjYyOTc2NTIyLCJleHAiOjE5NzgzMzY1MjJ9.rbbXK4jz7vS10CInuBvGnlp9Ul5C3qdBOVW-rRTAmeQ'
